// tb_blitter_trilist_pipe.sv — BLT_OP_TRILIST end-to-end equivalence test.
//
// Clones the DDR + P_SRC source models of tb_blitter_copy_pipe.sv, but drives a
// full TRILIST scene from vectors/tri_copy_ddr.hex (generated by gen_tri_golden.c)
// and diffs the ENTIRE composited comp_fbram against vectors/tri_copy_exp.hex
// (`FB_PIXELS RGB565 pixels) within +-1 LSB per channel.
//
// The control block (@0x200000) requests a CLEAR-before-list (blue bg) followed
// by one textured triangle; the vertex array + texture live at SRC (@0x210000).
// The tri walk composites into comp_fbram via the tri_busy bus muxes.
`timescale 1ns/1ps
`default_nettype none
`include "blitter_defs.vh"
module tb_blitter_trilist_pipe;
  localparam [28:0] WBASE = 29'h07400000;
  localparam        MEMQW = (`SRC_QW - 29'h07400000) + 29'h8000;

  reg clk=0, rst=1; always #5 clk=~clk;

  wire [31:0] bt_addr; wire b_rd, b_we; wire [63:0] b_din; wire [7:0] b_be; wire bt_idle;
  reg  d_dready; reg [63:0] d_dout;

  // behavioral DDR: single-beat reads w/ latency + backpressure.
  reg [63:0] mem [0:MEMQW-1];
  reg [7:0] rbeats; reg [28:0] raddr; reg [2:0] rlat; reg [1:0] bp=0;
  always @(posedge clk) bp <= bp+2'd1;
  wire d_busy = (bp != 2'd2) | (rbeats != 8'd0) | (rlat != 3'd0);
  integer i;

  // ── P_SRC cache-ok source model (serves texel reads from the SRC window) ─────
  localparam P_SRC_LAT = 3;
  localparam [28:0] SRC_WIN = `SRC_QW - WBASE;
  wire [26:0] s_src_addr; wire s_src_rd;
  reg  [63:0] s_src_dout; reg s_src_ok=1'b0;
  reg         s_rd_d;
  reg [26:0]  s_lat_addr [0:P_SRC_LAT-1];
  reg         s_lat_v    [0:P_SRC_LAT-1];
  integer     sli;
  always @(posedge clk) s_rd_d <= s_src_rd;
  // SINGLE-OUTSTANDING faithful line-cache model: hit=HIT_LAT, cold line-fill=MISS_LAT,
  // NLINES resident with LRU (rline[0]=MRU). Keyed by line = addr>>LINE_LOG2. Reproduces
  // the real jtframe ch5 behaviour (2 tiny lines the row-order texel walk thrashes) so a
  // prefetcher that issues reads AHEAD overlaps the miss latency and drops pb's stall
  // (texwait). Still single-outstanding + address-dependent variable phase, so it keeps
  // catching the p0_ok strobe-miss hang.
  localparam LINE_LOG2 = 8;    // 256-byte lines (tune with NLINES so texwait is ~30% of tri)
  localparam NLINES    = 2;    // faithful jtframe ch5 = 2 lines
  localparam HIT_LAT   = 4;
  localparam MISS_LAT  = 140;
  reg        so_busy = 1'b0;
  integer    so_cnt  = 0;
  reg [26:0] so_addr = 27'd0;
  reg [26:0] rline   [0:NLINES-1];   // resident line addrs, [0]=MRU
  reg        rline_v [0:NLINES-1];
  integer    li, hitpos;
  initial for (li=0; li<NLINES; li=li+1) begin rline[li]=27'h7FFFFFF; rline_v[li]=1'b0; end
  always @(posedge clk) begin
    s_src_ok <= 1'b0;
    if ((s_src_rd & ~s_rd_d) && !so_busy) begin
      so_busy <= 1'b1;
      so_addr <= s_src_addr;
      // LRU lookup on the accepted address' line.
      hitpos = -1;
      for (li=0; li<NLINES; li=li+1)
        if (rline_v[li] && (rline[li] == (s_src_addr >> LINE_LOG2))) hitpos = li;
      if (hitpos >= 0) begin
        so_cnt <= HIT_LAT;
        // promote to MRU
        for (li=0; li<NLINES; li=li+1) if (li <= hitpos && li>0) rline[li] <= rline[li-1];
        rline[0] <= (s_src_addr >> LINE_LOG2); rline_v[0] <= 1'b1;
      end else begin
        so_cnt <= MISS_LAT;
        // insert new line at MRU, shift others down, evict LRU
        for (li=NLINES-1; li>0; li=li-1) begin rline[li] <= rline[li-1]; rline_v[li] <= rline_v[li-1]; end
        rline[0] <= (s_src_addr >> LINE_LOG2); rline_v[0] <= 1'b1;
      end
    end
    if (so_busy) begin
      if (so_cnt <= 1) begin
        s_src_dout <= mem[SRC_WIN + (so_addr >> 3)];
        s_src_ok   <= 1'b1;
        so_busy    <= 1'b0;
      end else so_cnt <= so_cnt - 1;
    end
  end

  wire [7:0] bt_burst;
  wire fb_wr_en; wire [14:0] fb_wr_qw; wire [1:0] fb_wr_lane; wire [15:0] fb_wr_pix;
  wire fb_rd_en; wire [14:0] fb_rd_qw; wire [63:0] fb_rd_qword;
  comp_fbram fbram(.clk(clk),
    .wr_en(fb_wr_en), .wr_qw(fb_wr_qw), .wr_lane(fb_wr_lane), .wr_pix(fb_wr_pix),
    .rd_en(fb_rd_en), .rd_qw(fb_rd_qw), .rd_qword(fb_rd_qword));
  blitter_top blt(.clk(clk), .rst(rst),
    .mem_addr(bt_addr), .mem_rd(b_rd), .mem_wr(b_we), .mem_burstcnt(bt_burst),
    .mem_din(b_din), .mem_be(b_be),
    .mem_dout(d_dout), .mem_dout_ready(d_dready), .mem_busy(d_busy),
    .p0_addr(s_src_addr), .p0_rd(s_src_rd), .p0_dout(s_src_dout), .p0_ok(s_src_ok),
    .fb_wr_en(fb_wr_en), .fb_wr_qw(fb_wr_qw), .fb_wr_lane(fb_wr_lane), .fb_wr_pix(fb_wr_pix),
    .fb_rd_en(fb_rd_en), .fb_rd_qw(fb_rd_qw), .fb_rd_qword(fb_rd_qword),
    .idle(bt_idle));

  // [Phase 1 A2] NO-REGRESSION pin, not the win. This bench measures pb 6.04 cyc/px
  // BOTH before and after A2, because it never takes the dst-read path (dstw_cyc = 0,
  // measured) — it was already on the 6-cycle path. So the gate below CANNOT go red here
  // and is not evidence that A2 works. What it does pin is real and worth keeping: that
  // the tri_need_dst == FALSE path stayed at 6 and did not acquire an unconditional dst
  // read from the B_IDLE hoist. The 8.00 -> 6.00 win is demonstrated in
  // tb_blitter_trilist_add / tb_blitter_trilist_calpha, which do take the path.
  `define A2_PB_MAX 7.0
  `include "a2_cycle_gate.vh"

  // ── [Phase 1 A3] ring-select check ────────────────────────────────────────────
  // With C_SRCSEL bit 2 set, every command fetch must address ring B and NONE may
  // address ring A. Both directions are checked: a positive-only test would pass with
  // the selector hardwired to 1, and a stuck-at-0 selector is the failure this exists
  // to catch. Regions are derived from the macros, never retyped.
  //   ring A = [`RING_QW, `RING_B_QW)     ring B = [`RING_B_QW, `SRC_QW)
  // The control block sits BELOW `RING_QW (`BLTCTRL_QW + offsets 0..7), so control
  // reads/writes cannot trip the ring-A probe.
  reg a3_saw_ring_a, a3_saw_ring_b;
  initial begin a3_saw_ring_a = 1'b0; a3_saw_ring_b = 1'b0; end
  always @(posedge clk) if (b_rd) begin
    if ((bt_addr[28:0] >= `RING_QW)   && (bt_addr[28:0] < `RING_B_QW)) a3_saw_ring_a <= 1'b1;
    if ((bt_addr[28:0] >= `RING_B_QW) && (bt_addr[28:0] < `SRC_QW))    a3_saw_ring_b <= 1'b1;
  end

  task a3_check_ring_select;
    begin
      if (!a3_saw_ring_b) begin
        $display("FAIL A3: command fetch never addressed RING_B_QW with C_SRCSEL bit2 set");
        $finish;
      end
      if (a3_saw_ring_a) begin
        $display("FAIL A3: command fetch addressed ring A while C_SRCSEL bit2 was set");
        $finish;
      end
      $display("PASS A3: command fetch used ring B, and never ring A");
    end
  endtask

  always @(posedge clk) begin
    d_dready <= 1'b0;
    d_dout   <= 64'hDEAD_BEEF_DEAD_BEEF;
    if (rst) begin rbeats<=0; rlat<=0; end
    else begin
      if (rlat != 3'd0) rlat <= rlat - 3'd1;
      else if (rbeats != 8'd0) begin
        if (bp == 2'd2) begin
          d_dout <= mem[raddr-WBASE]; d_dready <= 1'b1;
          raddr <= raddr + 29'd1; rbeats <= rbeats - 8'd1;
        end
      end else if (!d_busy) begin
        if (b_rd) begin rbeats<=bt_burst; raddr<=bt_addr[28:0]; rlat<=3'd3; end
        else if (b_we) for(i=0;i<8;i=i+1) if(b_be[i]) mem[(bt_addr[28:0]-WBASE)][i*8 +:8]<=b_din[i*8 +:8];
      end
    end
  end

  // ── golden framebuffer (`FB_PIXELS RGB565 pixels, index = y*`FB_W+x) ────────────────
  reg [15:0] exp [0:`FB_PIXELS-1];

  integer x,y,idx,bad,ncov;
  reg [15:0] got, e;
  // ±1 LSB per RGB565 channel
  function integer chan_ok(input [15:0] a, input [15:0] b);
    integer dr,dg,db;
    begin
      dr = a[15:11] - b[15:11]; if (dr<0) dr=-dr;
      dg = a[10:5]  - b[10:5];  if (dg<0) dg=-dg;
      db = a[4:0]   - b[4:0];   if (db<0) db=-db;
      chan_ok = (dr<=1) && (dg<=1) && (db<=1);
    end
  endfunction

  // [Phase 1 A3] indices into `mem` (index = qword addr - WBASE), derived from the
  // canonical macros so a base move cannot silently desync this bench.
  localparam integer A3_CTRL_IDX  = `BLTCTRL_QW - WBASE;
  localparam integer A3_RINGA_IDX = `RING_QW    - WBASE;
  localparam integer A3_RINGB_IDX = `RING_B_QW  - WBASE;

  integer a3_i, a3_ncmd;
  initial begin
    for(i=0;i<MEMQW;i=i+1) mem[i]=64'd0;
    $readmemh("vectors/tri_copy_ddr.hex", mem);
    $readmemh("vectors/tri_copy_exp.hex", exp);

    // [Phase 1 A3] Move the whole command list to ring B, POISON ring A, and set the
    // selector — done here, at the tail of the block that loads the vectors, so the
    // ordering against $readmemh is deterministic rather than relying on #0 between
    // initial blocks.
    //
    // Ring A is poisoned with 64'd0 = OP_NOP (blitter_top.sv:199), which is DELIBERATE:
    // the fabric walks cmd_count NOPs and terminates cleanly via S_NEXT_CMD, so a
    // stuck-at-0 selector produces a BLANK framebuffer rather than a hang. That gives
    // two independent detections of the same fault — the ±1 LSB diff goes red AND the
    // address probe goes red — instead of a timeout that could be mistaken for anything.
    a3_ncmd = mem[A3_CTRL_IDX + `C_CMDCOUNT][31:0];
    for (a3_i = 0; a3_i < a3_ncmd*4; a3_i = a3_i + 1) begin
      mem[A3_RINGB_IDX + a3_i] = mem[A3_RINGA_IDX + a3_i];
      mem[A3_RINGA_IDX + a3_i] = 64'd0;
    end
    // Set ring-select, preserving every other bit — [15:8] is the LIVE f2h throttle.
    mem[A3_CTRL_IDX + `C_SRCSEL][`C_RINGSEL_BIT] = 1'b1;
    $display("A3 setup: %0d cmds relocated to ring B, ring A poisoned with OP_NOP, C_SRCSEL=%08h",
             a3_ncmd, mem[A3_CTRL_IDX + `C_SRCSEL][31:0]);
  end

  integer to;
  initial begin
    repeat(8) @(posedge clk); rst<=0;
    // run until done_seq == submit_seq, or timeout
    to=0;
    while (mem[32'h200005][31:0] !== mem[32'h200000][31:0] && to<4000000) begin @(posedge clk); to=to+1; end
    repeat(10) @(posedge clk);
    $display("=== done_seq=%0d submit=%0d (to=%0d) ===", mem[32'h200005][31:0], mem[32'h200000][31:0], to);

    // [profiling] datapath cyc/px from the S_TRI_* perf counters (this frame). The sim
    // stub gives P_SRC a fixed low latency, so texwait is small here; the DATAPATH cyc/px
    // (tri - texwait) is memory-independent and should track the device's ~41 cyc/px. Use
    // this as the iteration metric while pipelining the rasterizer toward 1 px/cyc.
    ncov=0;
    for (y=0;y<`FB_H;y=y+1) for (x=0;x<`FB_W;x=x+1) if (exp[y*`FB_W+x]!==exp[0]) ncov=ncov+1;
    $display("=== PERF tri=%0d texwait=%0d dpath=%0d covered_px=%0d | dpath_cyc/px=%0d ===",
             blt.perf_tri_cyc, blt.perf_texwait_cyc, blt.perf_tri_cyc-blt.perf_texwait_cyc,
             ncov, (ncov>0)?((blt.perf_tri_cyc-blt.perf_texwait_cyc)/ncov):0);

    // [Phase 1 A3] ring-select check runs FIRST, deliberately. Ring A is poisoned with
    // NOPs, so a ring-select fault renders nothing — which trips A2's "no pixels retired"
    // guard and would report a cycle-gate failure for what is really a ring fault.
    // Diagnosing the more fundamental fault first keeps the message honest.
    a3_check_ring_select;
    // [Phase 1 A2] cycle gate, before the framebuffer diff below. A cycle win with a
    // broken diff is not a win, so both must hold.
    a2_report_cycles;

    bad=0;
    for (y=0;y<`FB_H;y=y+1) for (x=0;x<`FB_W;x=x+1) begin
      idx = y*`FB_STRIDE_QW + (x>>2);
      got = ((x&3)==0) ? fbram.bank0[idx] : ((x&3)==1) ? fbram.bank1[idx] :
            ((x&3)==2) ? fbram.bank2[idx] : fbram.bank3[idx];
      e   = exp[y*`FB_W+x];
      // Golden-short trap: an entry past the end of the loaded vectors/*.hex reads
      // back x; x propagates through chan_ok and Verilog treats the resulting x as
      // FALSE, so the pixel would be silently NOT compared. That is exactly how this
      // bench passed vacuously before the geometry root landed — if FB_W/FB_H move
      // without regenerating vectors, fail loudly instead of re-opening the hole.
      // Guard BOTH sides: chan_ok() is symmetric in x-propagation (dr/dg/db are 4-state
      // integers), so chan_ok(x, real) also returns x and `!x` is x, which if() drops.
      // comp_fbram's banks have no sim initialisation, so an unwritten DUT pixel really
      // does read x and would be silently skipped. Reduction-XOR catches any x/z bit.
      if ((^e === 1'bx) || (^got === 1'bx)) begin
        bad=bad+1;
        if (bad<=20) $display("  UNDEFINED at (%0d,%0d): got=%04h exp=%04h — short golden (regenerate vectors) or unwritten FB pixel", x,y,got,e);
      end
      else if (!chan_ok(got,e)) begin
        bad=bad+1;
        if (bad<=20) $display("  MISMATCH (%0d,%0d): got %04h exp %04h", x,y,got,e);
      end
    end
    $display("=== bad pixels = %0d / %0d ===", bad, `FB_PIXELS);
    if (mem[32'h200005][31:0]==mem[32'h200000][31:0] && bad==0) $display("RESULT: PASS");
    else $display("RESULT: FAIL (bad=%0d)", bad);
    $finish;
  end
  // hard watchdog backstop
  initial begin #200000000 $display("RESULT: FAIL (timeout)"); $finish; end
endmodule
`default_nettype wire
